image:
  repository: tccr.io/truecharts/darktable
  pullPolicy: IfNotPresent
  tag: 4.0.1@sha256:af4e714a464a3eae5cea855f9947e0fc363a215a30e5ef3ef0c0cd5edbe9bcc4

securityContext:
  runAsNonRoot: false
  readOnlyRootFilesystem: false

podSecurityContext:
  runAsUser: 0
  runAsGroup: 0

service:
  main:
    ports:
      main:
        targetPort: 3000
        port: 10129

persistence:
  config:
    enabled: true
    mountPath: "/config"
  varrun:
    enabled: true

portal:
  enabled: true
