image:
  repository: tccr.io/truecharts/kavitaemail
  pullPolicy: IfNotPresent
  tag: 0.1.16@sha256:ca6dda73f5c449331e7c95449b0127a53715cab1e5c46e847d47f2c678c7d967

securityContext:
  runAsNonRoot: false
  readOnlyRootFilesystem: false

podSecurityContext:
  runAsUser: 0
  runAsGroup: 0

secretEnv:
  SMTP_USER: ""
  SMTP_PASS: ""

env:
  DISP_NAME: kavita
  SMTP_HOST: ""
  SMTP_PORT: 587
  SEND_ADDR: ""

service:
  main:
    ports:
      main:
        protocol: HTTP
        port: 15003
        targetPort: 5003

persistence:
  config:
    enabled: false
    mountPath: /app/config

portal:
  enabled: false
