image:
  repository: tccr.io/truecharts/wizarr
  pullPolicy: IfNotPresent
  tag: 2.1.3@sha256:00d3ce9ee145ba2f62a3789c80f9db6ab221dcfa7b1171ca45113aca26bccca3

env:
  APP_URL: "http://localhost:{{ .Values.service.main.ports.main.port }}"
  DISABLE_BUILTIN_AUTH: false
  ALLOW_BUG_REPORTING: false

service:
  main:
    ports:
      main:
        protocol: HTTP
        targetPort: 5690
        port: 10596

persistence:
  database:
    enabled: true
    mountPath: /data/database

portal:
  enabled: true
