image:
  pullPolicy: IfNotPresent
  repository: tccr.io/truecharts/duplicacy
  tag: latest@sha256:aadbbf95f3c15e779db1254ccc8dc4ece9f832f667481e1e0fa224b10fcb0b91

podSecurityContext:
  runAsGroup: 0
  runAsUser: 0

securityContext:
  readOnlyRootFilesystem: false
  runAsNonRoot: false

service:
  main:
    ports:
      main:
        port: 3875
        protocol: HTTP
        targetPort: 3875

persistence:
  config:
    enabled: true
    mountPath: /config
  cache:
    enabled: true
    mountPath: /cache
  logs:
    enabled: true
    mountPath: /logs

portal:
  enabled: true
