image:
  repository: tccr.io/truecharts/dupeguru
  tag: 23.03.1@sha256:d3a529039fb79c1ee33398ca77278d754488b0e6b1ab5598c415982ef44e46c4
  pullPolicy: IfNotPresent

securityContext:
  readOnlyRootFilesystem: false
  runAsNonRoot: false

podSecurityContext:
  runAsUser: 0
  runAsGroup: 0

service:
  main:
    ports:
      main:
        port: 10260
        targetPort: 5800
  vnc:
    enabled: true
    ports:
      vnc:
        enabled: true
        port: 10261
        targetPort: 5900

envFrom:
  - configMapRef:
      name: '{{ include "tc.common.names.fullname" . }}-dupeguru'

secretEnv:
  VNC_PASSWORD: ""

dupeguru:
  KEEP_APP_RUNNING: false
  DISPLAY_WIDTH: 1280
  DISPLAY_HEIGHT: 768
  SECURE_CONNECTION: false
  ENABLE_CJK_FONT: false

configmap:
  dupeguru:
    enabled: true
    data:
      ENABLE_CJK_FONT: '{{ ternary "1" "0" .Values.dupeguru.ENABLE_CJK_FONT }}'
      KEEP_APP_RUNNING: '{{ ternary "1" "0" .Values.dupeguru.KEEP_APP_RUNNING }}'
      SECURE_CONNECTION: '{{ ternary "1" "0" .Values.dupeguru.SECURE_CONNECTION }}'
      DISPLAY_WIDTH: "{{ .Values.dupeguru.DISPLAY_WIDTH }}"
      DISPLAY_HEIGHT: "{{ .Values.dupeguru.DISPLAY_HEIGHT }}"

persistence:
  config:
    enabled: true
    mountPath: "/config"
  storage:
    enabled: true
    mountPath: "/storage"
  trash:
    enabled: true
    mountPath: "/trash"

portal:
  enabled: true
