image:
  repository: tccr.io/truecharts/midarr-server
  tag: 3.0.0@sha256:71d20239afd03e457bce67234880e819979f45e296a5279e80cc57836a626d9a
  pullPolicy: IfNotPresent

securityContext:
  readOnlyRootFilesystem: false
  runAsNonRoot: false

podSecurityContext:
  runAsUser: 0
  runAsGroup: 0

midarr:
  admin:
    mail: admin@example.com
    name: admin
    pass: password
  general:
    app_url: http://localhost:4000
    app_mailer_from: midarr@example.com
    sendgrid_api_key: ""
  radarr:
    base_url: ""
    api_key: ""
  sonarr:
    base_url: ""
    api_key: ""

envFrom:
  - secretRef:
      name: '{{ include "tc.common.names.fullname" . }}-secret'
  - configMapRef:
      name: '{{ include "tc.common.names.fullname" . }}-config'

service:
  main:
    ports:
      main:
        port: 10347
        protocol: HTTP
        targetPort: 4000

postgresql:
  enabled: true
  existingSecret: dbcreds
  postgresqlUsername: midarr
  postgresqlDatabase: midarr

portal:
  enabled: true
