image:
  pullPolicy: IfNotPresent
  repository: tccr.io/truecharts/phpmyadmin
  tag: latest@sha256:834e6b4d7874f50dc711a5542f1d16be9bf26e9ec4e9782999f2a7ddc9f511a3

podSecurityContext:
  runAsGroup: 0
  runAsUser: 0

securityContext:
  readOnlyRootFilesystem: false
  runAsNonRoot: false

env:
  MYSQL_PASSWORD: root
  MYSQL_USER: root
  PMA_HOST: 192.168.70.99
  PMA_PORT: "3306"
  # PMA_ABSOLUTE_URI: ""

service:
  main:
    ports:
      main:
        port: 8080
        protocol: HTTP
        targetPort: 80

portal:
  enabled: true
