env:
  EULA: "false"
  JVM_OPTS: -Xms6144m -Xmx8192m
  OPS: ""
image:
  pullPolicy: IfNotPresent
  repository: tccr.io/truecharts/vaulthunters
  tag: latest@sha256:1c32caaa27303f70bf3a56379956dea1b833518b50182268f5cb8228772ccc59
persistence:
  data:
    enabled: true
    mountPath: /data
podSecurityContext:
  runAsGroup: 0
  runAsUser: 0
securityContext:
  readOnlyRootFilesystem: false
  runAsNonRoot: false
service:
  main:
    ports:
      main:
        port: 25565
        protocol: TCP
        targetPort: 25565

portal:
  enabled: true
