image:
  pullPolicy: IfNotPresent
  repository: tccr.io/truecharts/factorio
  tag: vstable@sha256:ee2ee2506598c0b7a875f922d3aef78dca72adeb4e36677751f7f668a7a2b0f7

podSecurityContext:
  runAsGroup: 0
  runAsUser: 0

probes:
  liveness:
    enabled: false
  readiness:
    enabled: false
  startup:
    enabled: false

securityContext:
  readOnlyRootFilesystem: false
  runAsNonRoot: false

env:
  GENERATE_NEW_SAVE: false
  LOAD_LATEST_SAVE: true
  SAVE_NAME: "_autosave1"
  TOKEN: ""
  UPDATE_MODS_ON_START: ""
  USERNAME: ""

service:
  main:
    ports:
      main:
        port: 34197
        protocol: UDP
        targetPort: 34197
  rcon:
    enabled: true
    ports:
      rcon:
        enabled: true
        port: 27015
        protocol: TCP
        targetPort: 27015

persistence:
  path:
    enabled: true
    mountPath: /factorio

portal:
  enabled: false
