image:
  pullPolicy: IfNotPresent
  repository: tccr.io/truecharts/tasmoadmin
  tag: 3.0.2@sha256:bde0ac7275320b2ee37fc60dfc94f209fbe21ef2dbc1f99487a3aebfc9f8005f

podSecurityContext:
  runAsGroup: 0
  runAsUser: 0

securityContext:
  readOnlyRootFilesystem: false
  runAsNonRoot: false

env:
  TASMO_DATADIR: /data
  TASMO_DEBUG: 1

service:
  main:
    ports:
      main:
        port: 9541
        protocol: HTTP
        targetPort: 80

persistence:
  data:
    enabled: true
    mountPath: /data

portal:
  enabled: true
