image:
  repository: tccr.io/truecharts/wireshark
  pullPolicy: IfNotPresent
  tag: 4.0.1@sha256:92585ec8db165aaec6de097790a843b59395d896d8e32bcb2b08897afba481d2

securityContext:
  readOnlyRootFilesystem: false
  runAsNonRoot: false
  capabilities:
    add:
      - NET_ADMIN

podSecurityContext:
  runAsUser: 0
  runAsGroup: 0

hostNetwork: true

service:
  main:
    ports:
      main:
        targetPort: 3000
        protocol: HTTP
        port: 3000

probes:
  liveness:
    path: /
  readiness:
    path: /
  startup:
    path: /

persistence:
  varrun:
    enabled: true
  config:
    enabled: true
    mountPath: /config

portal:
  enabled: true
