image:
  pullPolicy: IfNotPresent
  repository: tccr.io/truecharts/thunderbird
  tag: latest@sha256:3f8000da2c6477641e855350f5465db4ce5a4f86f969dd798a5af40a2b36c4b5

podSecurityContext:
  runAsGroup: 0
  runAsUser: 0

securityContext:
  readOnlyRootFilesystem: false
  runAsNonRoot: false

env:
  THUNDERBIRD_V: "latest"
  CUSTOM_RES_H: 768
  CUSTOM_RES_W: 1280
  DATA_PERM: 770
  THUNDERBIRD_LANG: "en-US"

service:
  main:
    ports:
      main:
        port: 10291
        targetPort: 8080

persistence:
  data:
    enabled: true
    mountPath: /thunderbird

portal:
  enabled: true
