image:
  repository: tccr.io/truecharts/scrypted-thin
  pullPolicy: IfNotPresent
  tag: 0.6.26@sha256:5a36daa3b248f1f1f8c5705134d29b2b92e64e40f3a7d675465748dfe6c2d4f8

liteImage:
  repository: tccr.io/truecharts/scrypted-lite
  tag: 0.6.26@sha256:26ae404636b8ce9231420c6685ab35c72ca884678cb9a49ea38bba00e6fe284a
  pullPolicy: Always

fullImage:
  repository: tccr.io/truecharts/scrypted-full
  tag: 0.6.26@sha256:3c0fe2ac944cf077d40048c8e2dd0b776f868a250bccab29e5b13d7b96482299
  pullPolicy: Always

imageSelector: image

securityContext:
  readOnlyRootFilesystem: false
  runAsNonRoot: false

podSecurityContext:
  runAsUser: 0
  runAsGroup: 0

env:
  SCRYPTED_INSECURE_PORT: "{{ .Values.service.main.ports.main.port }}"
  # SCRYPTED_WEBHOOK_UPDATE_AUTHORIZATION: Bearer SET_THIS_TO_SOME_RANDOM_TEXT
  # SCRYPTED_WEBHOOK_UPDATE: http://localhost:10444/v1/update

service:
  main:
    ports:
      main:
        protocol: HTTP
        port: 10611

persistence:
  server:
    enabled: true
    mountPath: /server/volume
  media:
    enabled: true
    mountPath: /media/external

portal:
  enabled: true
