image:
  repository: tccr.io/truecharts/scrypted-thin
  pullPolicy: IfNotPresent
  tag: 0.7.97@sha256:50579ec8d3442aed8d4bfdbfef47375f777e44f135aff983a7ca6bde4d79acbb

liteImage:
  repository: tccr.io/truecharts/scrypted-lite
  tag: 0.7.97@sha256:082871cb3b4bfd1906e5cdb78de28b20a8ac714cd8f820de519be94de4193860
  pullPolicy: Always

fullImage:
  repository: tccr.io/truecharts/scrypted-full
  tag: 0.7.97@sha256:93cf72272244f9e93e6830ad3f7f99148e91bcb40127aea43d860376ab189a97
  pullPolicy: Always

imageSelector: image

securityContext:
  readOnlyRootFilesystem: false
  runAsNonRoot: false

podSecurityContext:
  runAsUser: 0
  runAsGroup: 0

env:
  SCRYPTED_INSECURE_PORT: "{{ .Values.service.main.ports.main.port }}"
  # SCRYPTED_WEBHOOK_UPDATE_AUTHORIZATION: Bearer SET_THIS_TO_SOME_RANDOM_TEXT
  # SCRYPTED_WEBHOOK_UPDATE: http://localhost:10444/v1/update

service:
  main:
    ports:
      main:
        protocol: HTTP
        port: 10611

persistence:
  server:
    enabled: true
    mountPath: /server/volume
  media:
    enabled: true
    mountPath: /media/external

portal:
  enabled: true
