image:
  repository: tccr.io/truecharts/nexusoss
  pullPolicy: IfNotPresent
  tag: 3.52.0@sha256:97ba3ffcef8b568b97ebe7fcb76e55ef74ea4e90064d27c97801f31bb120bc5a

podSecurityContext:
  runAsGroup: 200
  runAsUser: 200
  fsGroup: 200

env:
  INSTALL4J_ADD_VM_PARAMS: "-Xms2703m -Xmx2703m -XX:MaxDirectMemorySize=2703m -Djava.util.prefs.userRoot=${NEXUS_DATA}/javaprefs"

service:
  main:
    ports:
      main:
        port: 10288
        targetPort: 8081

persistence:
  data:
    enabled: true
    mountPath: /nexus-data

portal:
  enabled: true
