image:
  repository: tccr.io/truecharts/inventree
  tag: 0.11.0@sha256:00e9c599fb574afd36bbd9ca01b209ddb004f26974d937a8f56c8a3cd720355e
  pullPolicy: IfNotPresent

nginxImage:
  repository: tccr.io/truecharts/nginx
  tag: 1.23.4@sha256:7e6b4bc511d01b48171cb3c345a67802297c77143c1411e22c5cf7e8acbf1915
  pullPolicy: IfNotPresent

securityContext:
  readOnlyRootFilesystem: false
  runAsNonRoot: false
# https://github.com/inventree/InvenTree/pull/3096
podSecurityContext:
  runAsUser: 0
  runAsGroup: 0

envFrom:
  - secretRef:
      name: '{{ include "tc.common.names.fullname" . }}-inventree-secret'
  - configMapRef:
      name: '{{ include "tc.common.names.fullname" . }}-inventree-config'

inventree:
  credentials:
    admin_mail: "test@example.com"
    admin_user: "testuser"
    admin_password: "secret"
  general:
    debug: false
    log_level: "INFO"
    plugins_enabled: false
    login_confirm_days: 3
    login_attempts: 5
  mail:
    backend: "django.core.mail.backends.smtp.EmailBackend"
    host: ""
    port: 587
    username: ""
    password: ""
    tls: false
    ssl: false
    sender: ""

service:
  main:
    ports:
      main:
        port: 10231

persistence:
  data:
    enabled: true
    mountPath: "/home/inventree/data"
  inventree-nginx:
    enabled: true
    noMount: true
    type: custom
    mountPath: "/etc/nginx/conf.d"
    volumeSpec:
      configMap:
        name: '{{ include "tc.common.names.fullname" . }}-inventree-config-nginx'
        items:
          - key: nginx.conf
            path: default.conf

postgresql:
  enabled: true
  existingSecret: "dbcreds"
  postgresqlUsername: inventree
  postgresqlDatabase: inventree

redis:
  enabled: true
  existingSecret: "rediscreds"
  redisUsername: default

portal:
  enabled: true
