env:
  ELASTIC_PASSWORD: verysecret
  ES_JAVA_OPTS: -Xms512m -Xmx512m
  discovery.type: single-node
  xpack.security.enabled: "true"
image:
  pullPolicy: IfNotPresent
  repository: tccr.io/truecharts/tubearchivist-es
  tag: latest@sha256:faee01f8c2114c7caa8e6d7e157c8a43650e59222e8b03a01493ee97515038c5
persistence:
  data:
    enabled: true
    mountPath: /usr/share/elasticsearch/data
podSecurityContext:
  runAsGroup: 0
  runAsUser: 0
securityContext:
  readOnlyRootFilesystem: false
  runAsNonRoot: false
service:
  main:
    ports:
      main:
        port: 9200
        protocol: TCP
        targetPort: 9200

portal:
  enabled: true
