image:
  repository: tccr.io/truecharts/upsnap
  pullPolicy: IfNotPresent
  tag: 3.2.6@sha256:fee426e26d391aada31616ce6b21960f7975c68194d08159874bf5a49debcc47

securityContext:
  readOnlyRootFilesystem: false
  runAsNonRoot: false

podSecurityContext:
  runAsUser: 0
  runAsGroup: 0

hostNetwork: true

env:
  UPSNAP_INTERVAL: "@every 10s"
  UPSNAP_SCAN_RANGE: 192.168.1.0/24
  UPSNAP_WEBSITE_TITLE: Truecharts WOL

service:
  main:
    ports:
      main:
        protocol: HTTP
        targetPort: 8090
        port: 10611

persistence:
  data:
    enabled: true
    mountPath: /app/pb_data

portal:
  enabled: true
