image:
  repository: tccr.io/truecharts/filezilla
  pullPolicy: IfNotPresent
  tag: 3.62.1@sha256:92f25ceb7c6dd034ac827ba7e6a2f2fb68a70186e2ab12191de1e89cb657eff0

securityContext:
  readOnlyRootFilesystem: false
  runAsNonRoot: false

podSecurityContext:
  runAsUser: 0
  runAsGroup: 0

service:
  main:
    ports:
      main:
        port: 10035
        targetPort: 3000

persistence:
  config:
    enabled: true
    mountPath: "/config"
  varrun:
    enabled: true

portal:
  enabled: true
