image:
  pullPolicy: IfNotPresent
  repository: tccr.io/truecharts/cleanarr
  tag: 2.2.2@sha256:576009190156abd21adc05ec65af1d3ff4cb09614992da43494638fcbf39ad72

podSecurityContext:
  runAsGroup: 0
  runAsUser: 0
securityContext:
  readOnlyRootFilesystem: false
  runAsNonRoot: false

env:
  BYPASS_SSL_VERIFY: '{{ ternary "1" "0" .Values.env.BYPASS_SSL_VERIFY_BOOL }}'
  # User defined
  BYPASS_SSL_VERIFY_BOOL: true
  LIBRARY_NAMES: ""
  PLEX_BASE_URL: ""
  PLEX_TOKEN: ""
  PAGE_SIZE: 50

service:
  main:
    ports:
      main:
        protocol: HTTP
        port: 10247
        targetPort: 80

persistence:
  config:
    enabled: true
    mountPath: /config

portal:
  enabled: true
