image:
  pullPolicy: IfNotPresent
  repository: tccr.io/truecharts/searx
  tag: latest@sha256:3415e366561f1c97ae9c8f339de7f936b76881199fea917469ad3ca2ef020cef

podSecurityContext:
  runAsGroup: 0
  runAsUser: 0

securityContext:
  readOnlyRootFilesystem: false
  runAsNonRoot: false

env:
  BASE_URL: ""

service:
  main:
    ports:
      main:
        port: 8080
        protocol: TCP
        targetPort: 8080

persistence:
  config:
    enabled: true
    mountPath: /etc/searx

portal:
  enabled: true
