image:
  repository: tccr.io/truecharts/misskey
  pullPolicy: IfNotPresent
  tag: 13.11.3@sha256:dedc84c2e68aa0b66db5cf174fc89a5eb4f14321f3f8c047cb35ac22a8cbb40f

securityContext:
  readOnlyRootFilesystem: false
  runAsNonRoot: false

podSecurityContext:
  runAsUser: 0
  runAsGroup: 0
  fsGroup: 33

service:
  main:
    ports:
      main:
        port: 3003

misskey:
  # Final accessible URL seen by a user. ONCE YOU HAVE STARTED THE INSTANCE, DO NOT CHANGE THE URL SETTINGS AFTER THAT!
  url: "https://example.tld/"
  # ID generation method. 'aid' recommended.
  id: "aid"
  other:
    disableHSTS: false
    signToActivityPubGet: false
    maxFileSize: 262144000
    clusterLimit: 1
    deliverJobConcurrency: 128
    inboxJobConcurrency: 16
    deliverJobPerSec: 128
    inboxJobPerSec: 16
    deliverJobMaxAttempts: 12
    inboxJobMaxAttempts: 8
    allowedPrivateNetworks:
      - 127.0.0.1/32

env:
  # NODE_ENV = production | development
  NODE_ENV: production

persistence:
  misskeyconfig:
    enabled: true
    type: configMap
    objectName: misskeyconfig
    mountPath: "/misskey/.config"
  files:
    enabled: true
    mountPath: "/misskey/files"

postgresql:
  enabled: true
  existingSecret: "dbcreds"
  postgresqlUsername: misskey
  postgresqlDatabase: misskey

redis:
  enabled: true
  existingSecret: "rediscreds"

portal:
  enabled: true
