image:
  repository: tccr.io/truecharts/darktable
  pullPolicy: IfNotPresent
  tag: 3.8.1@sha256:3d47d9bf9099e76a172b375934e005a5f47e8dd7e57c86843763c867cf342963

securityContext:
  container:
    runAsNonRoot: false
    readOnlyRootFilesystem: false
    runAsUser: 0
    runAsGroup: 0

service:
  main:
    ports:
      main:
        port: 3000
        protocol: http

workload:
  main:
    podSpec:
      containers:
        main:
          probes:
            liveness:
              type: tcp
            readiness:
              type: tcp
            startup:
              type: tcp

persistence:
  config:
    enabled: true
    mountPath: /config

portal:
  open:
    enabled: true
