env: {}
image:
  pullPolicy: IfNotPresent
  repository: tccr.io/truecharts/cadquery-jupyter
  tag: 3.5.2@sha256:8b5e2e252b8b4b28129fd4a717ade42f25d01401f44480a5bb7daa7e6b2e13ef
persistence:
  workdir:
    enabled: true
    mountPath: /home/cq
podSecurityContext:
  runAsGroup: 0
  runAsUser: 0
securityContext:
  readOnlyRootFilesystem: false
  runAsNonRoot: false
service:
  main:
    ports:
      main:
        port: 8888
        protocol: TCP
        targetPort: 8888

portal:
  enabled: true
