image:
  repository: tccr.io/truecharts/pidgin
  pullPolicy: IfNotPresent
  tag: 2.14.10@sha256:93e0659e846f9cce8d3911d4fa7a7d2bc1f940fa34efa0cd8b78f38d42f6d832

securityContext:
  runAsNonRoot: false
  readOnlyRootFilesystem: false

podSecurityContext:
  runAsUser: 0
  runAsGroup: 0

service:
  main:
    ports:
      main:
        targetPort: 3000
        port: 10136

persistence:
  config:
    enabled: true
    mountPath: "/config"
  varrun:
    enabled: true

portal:
  enabled: true
