image:
  repository: tccr.io/truecharts/rickroll
  pullPolicy: IfNotPresent
  tag: latest@sha256:dfd2479839f9632a71a0ba350d3dfcda0fa2af2ce88bea19cf71907d33084d6f
fhdImage:
  repository: tccr.io/truecharts/rickroll-fhd
  pullPolicy: IfNotPresent
  tag: latest@sha256:bc833e52ed8bb0e0abbd110c2afbb94a8ac794f8d5c758ad9ba992f2f75b1e14
fhdgameImage:
  repository: tccr.io/truecharts/rickroll-fhd-game
  pullPolicy: IfNotPresent
  tag: latest@sha256:ab13300ce0913219cd2f5bf4a390901185c4e51411e1be9fb25280c028f7af25
fhdonclickImage:
  repository: tccr.io/truecharts/rickroll-fhd-onclick
  pullPolicy: IfNotPresent
  tag: latest@sha256:a55428843ae3de037b1b346b1200eb6bc58fb661acc970e8dbffe7a255a45048
onclickImage:
  repository: tccr.io/truecharts/rickroll-onclick
  pullPolicy: IfNotPresent
  tag: latest@sha256:7d0de2cc4f19c2b8a92f86a8282f1216cd7db5ee19c44de53b7516ddba2829ab

imageSelector: "image"

securityContext:
  readOnlyRootFilesystem: false
  runAsNonRoot: false

podSecurityContext:
  runAsGroup: 0
  runAsUser: 0

service:
  main:
    ports:
      main:
        protocol: HTTP
        targetPort: 8080
        port: 10289

portal:
  enabled: true
