image:
  repository: tccr.io/truecharts/noisedash
  tag: 0.6.11@sha256:7f46d48b3a96217d5f687c85fd7a5d7a87cf437fd946787a2d44aa11cfb36d56
  pullPolicy: IfNotPresent

securityContext:
  readOnlyRootFilesystem: false
  runAsNonRoot: false

podSecurityContext:
  runAsUser: 0
  runAsGroup: 0

noisedash:
  max_sample_size_in_bytes: 10737418240

service:
  main:
    ports:
      main:
        port: 10328

persistence:
  db:
    enabled: true
    mountPath: /var/noisedash/db
  samples:
    enabled: true
    mountPath: /var/noisedash/samples

portal:
  enabled: true
