image:
  repository: tccr.io/truecharts/putty
  tag: 23.02.2@sha256:4bec4d770722ee284dcb7db8250768a62d72a5f29c54ed547458c2450f0676a5
  pullPolicy: IfNotPresent
service:
  main:
    ports:
      main:
        port: 10266
        targetPort: 5800
  vnc:
    enabled: true
    ports:
      vnc:
        enabled: true
        port: 10267
        targetPort: 5900
putty:
  KEEP_APP_RUNNING: false
  DISPLAY_WIDTH: 1280
  DISPLAY_HEIGHT: 768
  SECURE_CONNECTION: false
  DISABLE_RESTART_SESSION_DIALOG_WINDOW: false
  ENABLE_CJK_FONT: false
configmap:
  putty:
    enabled: true
    data:
      ENABLE_CJK_FONT: '{{ ternary "1" "0" .Values.putty.ENABLE_CJK_FONT }}'
      KEEP_APP_RUNNING: '{{ ternary "1" "0" .Values.putty.KEEP_APP_RUNNING }}'
      SECURE_CONNECTION: '{{ ternary "1" "0" .Values.putty.SECURE_CONNECTION }}'
      DISABLE_RESTART_SESSION_DIALOG_WINDOW: '{{ ternary "1" "0" .Values.putty.DISABLE_RESTART_SESSION_DIALOG_WINDOW }}'
      DISPLAY_WIDTH: "{{ .Values.putty.DISPLAY_WIDTH }}"
      DISPLAY_HEIGHT: "{{ .Values.putty.DISPLAY_HEIGHT }}"
persistence:
  config:
    enabled: true
    mountPath: "/config"
portal:
  open:
    enabled: true
securityContext:
  container:
    readOnlyRootFilesystem: false
    runAsNonRoot: false
    runAsUser: 0
    runAsGroup: 0
workload:
  main:
    podSpec:
      containers:
        main:
          securityContext:
            capabilities:
              add:
                - NET_BIND_SERVICE
                - KILL
          probes:
            liveness:
              type: tcp
            readiness:
              type: tcp
            startup:
              type: tcp
          env:
            VNC_PASSWORD: ""
          envFrom:
            - configMapRef:
                name: "putty"
