image:
  repository: tccr.io/truecharts/cups-server
  tag: latest@sha256:59406e559958b0d99b39a936c0dc66ee8dbb16e59a4ee4edb6fc8de68f02255b
  pullPolicy: IfNotPresent

securityContext:
  readOnlyRootFilesystem: false
  runAsNonRoot: false

podSecurityContext:
  runAsUser: 0
  runAsGroup: 0

secretEnv:
  ADMIN_PASSWORD: "secretpass"

service:
  main:
    ports:
      main:
        port: 631
        targetPort: 631

persistence:
  config:
    enabled: true
    mountPath: "/etc/cups"
  dbus:
    enabled: true
    type: hostPath
    hostPath: "/var/run/dbus"
    mountPath: "/var/run/dbus"
    readOnly: false

portal:
  enabled: true
