image:
  repository: tccr.io/truecharts/firefox
  pullPolicy: IfNotPresent
  tag: 109.0.1@sha256:6edc9ae7fe5450af2f129449908a1d868e5cff049d8471572c68f15e08bfc6a7

securityContext:
  runAsNonRoot: false
  readOnlyRootFilesystem: false

podSecurityContext:
  runAsUser: 0
  runAsGroup: 0

service:
  main:
    ports:
      main:
        targetPort: 3000
        port: 10131

persistence:
  config:
    enabled: true
    mountPath: "/config"
  varrun:
    enabled: true

portal:
  enabled: true
