image:
  repository: tccr.io/truecharts/openproject
  pullPolicy: IfNotPresent
  tag: 12.5.3@sha256:3c4113eef51839d85b0ebcd52cb24f9648e592a0578bc6acf3b08de8b944bd6f

securityContext:
  readOnlyRootFilesystem: false
  runAsNonRoot: false

podSecurityContext:
  runAsGroup: 0
  runAsUser: 0

env:
  SECRET_KEY_BASE:
    secretKeyRef:
      name: openproject-secrets
      key: SECRET_KEY_BASE
  DATABASE_URL:
    secretKeyRef:
      name: dbcreds
      key: url-noql

persistence:
  assets:
    enabled: true
    mountPath: /var/openproject/assets

service:
  main:
    ports:
      main:
        port: 10290
        targetPort: 80

postgresql:
  enabled: true
  existingSecret: "dbcreds"
  postgresqlUsername: openproject
  postgresqlDatabase: openproject

portal:
  enabled: true
