image:
  repository: tccr.io/truecharts/serpbear
  pullPolicy: IfNotPresent
  tag: latest@sha256:e80141bee34637846798e09ebb1b0ba47e128dc77b87fce779f0519e5f2cde60

serpbear:
  user: admin
  password: secret
  session_duration: 24
  api_key: ""
  app_url: http://localhost:10605

envFrom:
  - secretRef:
      name: '{{ include "tc.common.names.fullname" . }}-env-secret'

service:
  main:
    ports:
      main:
        protocol: HTTP
        targetPort: 3000
        port: 10605

persistence:
  data:
    enabled: true
    mountPath: /app/data

portal:
  enabled: true
