image:
  repository: tccr.io/truecharts/ersatztv
  pullPolicy: IfNotPresent
  tag: 0.7.7@sha256:915cf27fa3b7c1cdc3c897c12320afa046868ddc9a8851ab39522694e2a31c89
nvidiaImage:
  repository: tccr.io/truecharts/ersatztv-nvidia
  tag: 0.7.7@sha256:3f2c8f48ee4c2818a521ae623642cc4e5b726555a87c3d76677667041e7fad8c
  pullPolicy: Always
vaapiImage:
  repository: tccr.io/truecharts/ersatztv-vaapi
  tag: 0.7.7@sha256:4141b82a156b08ef881854b591425a63ee765707b422c05711a99084f1843e57
  pullPolicy: Always

imageSelector: image

securityContext:
  runAsNonRoot: false
  readOnlyRootFilesystem: false

podSecurityContext:
  runAsUser: 0
  runAsGroup: 0

probes:
  liveness:
    type: HTTP
  readiness:
    type: HTTP
  startup:
    type: HTTP

service:
  main:
    ports:
      main:
        protocol: HTTP
        targetPort: 8409
        port: 10607

persistence:
  config:
    enabled: true
    mountPath: /root/.local/share/ersatztv
  varrun:
    enabled: true

portal:
  enabled: true
