image:
  pullPolicy: IfNotPresent
  repository: tccr.io/truecharts/searxng
  tag: latest@sha256:83b6d394e40a875321a1c3f9ba233965152e441acb4193b7df4ac4862edbd25b

env:
  BASE_URL: ""
  INSTANCE_NAME: SearXng

podSecurityContext:
  runAsGroup: 0
  runAsUser: 0

securityContext:
  readOnlyRootFilesystem: false
  runAsNonRoot: false

service:
  main:
    ports:
      main:
        port: 8080
        protocol: TCP
        targetPort: 8080

persistence:
  config:
    enabled: true
    mountPath: /etc/searxng

portal:
  enabled: true
