image:
  repository: tccr.io/truecharts/libreoffice
  pullPolicy: IfNotPresent
  tag: 7.3.7@sha256:53b3b42942760b1c5abcf732558592f3b41ba43dae106b8a62c3aa2a2d09503f

securityContext:
  runAsNonRoot: false
  readOnlyRootFilesystem: false

podSecurityContext:
  runAsUser: 0
  runAsGroup: 0

service:
  main:
    ports:
      main:
        targetPort: 3000
        port: 10133

persistence:
  config:
    enabled: true
    mountPath: "/config"
  varrun:
    enabled: true

portal:
  enabled: true
