env:
  CUSTOM_RES_H: "768"
  CUSTOM_RES_W: "1280"
  EXTRA_PARAMETERS: ""
  NOVNC_RESIZE: remote
  UG_CHROMIUM_V: latest@sha256:f0065aa44fb1c38b7fc30d34e220138dc0a0c6477b78eb7f59015622c2052030
  UMASK: "000"
image:
  pullPolicy: IfNotPresent
  repository: tccr.io/truecharts/ungoogled-chromium
  tag: latest@sha256:dcbdecfb43582867c545e7ea7b88971dd7d6ba4eb5504d374dd96b34c4193b54
persistence:
  datadir:
    enabled: true
    mountPath: /ungoogledchromium
podSecurityContext:
  runAsGroup: 0
  runAsUser: 0
securityContext:
  readOnlyRootFilesystem: false
  runAsNonRoot: false
service:
  main:
    ports:
      main:
        port: 8080
        protocol: TCP
        targetPort: 8080

portal:
  enabled: true
